-- PRODUCTS
INSERT INTO products (name, price, category, image, amount_in_stock, has_allergens) VALUES
    ('Almonds', 5.99, 'Nuts', 'static/almonds.png', 100, 1),
    ('Banana', 0.99, 'Fruits', 'static/bannana.png', 200, 0),
    ('Brazil Nuts', 6.49, 'Nuts', 'static/brazilnuts.png', 80, 1),
    ('Chia Seeds', 4.99, 'Seeds', 'static/chiaseeds.png', 150, 0),
    ('Dragon Fruit', 7.99, 'Fruits', 'static/dragonfruit.png', 50, 0),
    ('Kiwi', 1.29, 'Fruits', 'static/kiwi.png', 120, 0),
    ('Nectarine', 2.49, 'Fruits', 'static/nectarin.png', 130, 0),
    ('Peach', 2.79, 'Fruits', 'static/peach.png', 140, 0),
    ('Pine Nuts', 8.99, 'Nuts', 'static/pinenuts.png', 70, 1),
    ('Quinoa', 3.99, 'Grains', 'static/quinoa.png', 160, 0),
    ('Tomatoes', 1.99, 'Vegetables', 'static/tomatoes.png', 180, 0),
    ('Apple', 1.49, 'Fruits', 'static/apple.png', 190, 0),
    ('Bell Pepper', 2.99, 'Vegetables', 'static/bellpepper.png', 110, 0),
    ('Carrots', 1.29, 'Vegetables', 'static/carrots.png', 210, 0),
    ('Chickpeas', 2.59, 'Legumes', 'static/chickpeas.png', 130, 0),
    ('Eggs', 3.99, 'Dairy', 'static/eggs.png', 120, 1),
    ('Lentils', 2.79, 'Legumes', 'static/lentils.png', 150, 0),
    ('Orange', 1.79, 'Fruits', 'static/orange.png', 160, 0),
    ('Pear', 1.89, 'Fruits', 'static/pear.png', 170, 0),
    ('Pistachios', 7.49, 'Nuts', 'static/pistachios.png', 90, 1),
    ('Spinach', 2.99, 'Vegetables', 'static/spinach.png', 140, 0),
    ('Walnuts', 6.99, 'Nuts', 'static/walnust.png', 85, 1),
    ('Avocado', 3.49, 'Fruits', 'static/avocado.png', 100, 0),
    ('Blueberries', 4.99, 'Fruits', 'static/blueberries.png', 120, 0),
    ('Cashews', 6.79, 'Nuts', 'static/cashews.png', 90, 1),
    ('Cucumber', 1.69, 'Vegetables', 'static/cucumber.png', 160, 0),
    ('Janis Kiploks', 9.99, 'Specialty', 'static/janiskiploks.png', 30, 0),
    ('Mango', 2.99, 'Fruits', 'static/mango.png', 100, 0),
    ('Papaya', 3.49, 'Fruits', 'static/papaya.png', 80, 0),
    ('Pineapple', 4.29, 'Fruits', 'static/pineapple.png', 90, 0),
    ('Potatoes', 1.49, 'Vegetables', 'static/potatoes.png', 200, 0),
    ('Strawberries', 5.49, 'Fruits', 'static/strawberries.png', 110, 0);

-- ALLERGENS
INSERT INTO allergens (name, image, info) VALUES
    ('Fish', 'static/fish.png', '{"What is Fish Allergy?":"A fish allergy occurs when the immune system mistakenly identifies proteins in fish as harmful, triggering an allergic reaction.","Allergic Reactions":"Symptoms can range from mild hives and swelling to severe anaphylaxis."}'),
    ('Milk', 'static/milk.png', '{"What is Milk Allergy?":"Milk allergy is an immune response to proteins found in cows milk, such as casein and whey.","Allergic Reactions":"Symptoms include skin rashes, vomiting, wheezing, and anaphylaxis."}'),
    ('Eggs', 'static/eggs.png', '{"What is Egg Allergy?":"Egg allergy occurs when the immune system reacts to proteins found in egg whites or yolks.","Allergic Reactions":"Symptoms may include skin hives, digestive issues, respiratory problems, and anaphylaxis."}'),
    ('Peanut', 'static/peanut.png', '{"What is Peanut Allergy?":"Peanut allergy is a common and potentially severe allergy caused by an immune system overreaction to peanut proteins.","Allergic Reactions":"Reactions range from mild itching and swelling to severe anaphylaxis."}'),
    ('Soy', 'static/soy.png', '{"What is Soy Allergy?":"Soy allergy is an immune system reaction to proteins found in soybeans.","Allergic Reactions":"Symptoms include hives, stomach pain, respiratory distress, and anaphylaxis."}'),
    ('Wheat', 'static/wheat.png', '{"What is Wheat Allergy?":"Wheat allergy is a reaction to proteins found in wheat, including gluten.","Allergic Reactions":"Reactions range from hives and nausea to severe anaphylaxis."}'),
    ('Tree Nuts', 'static/treenut.png', '{"What is Tree Nut Allergy?":"Tree nut allergy involves an immune reaction to nuts like almonds, walnuts, cashews, and pistachios.","Allergic Reactions":"Symptoms include swelling, difficulty breathing, and anaphylaxis."}'),
    ('Shellfish', 'static/shellfish.png', '{"What is Shellfish Allergy?":"Shellfish allergy is a reaction to proteins in crustaceans and mollusks.","Allergic Reactions":"Symptoms include skin rashes, gastrointestinal distress, and anaphylaxis."}'),
    ('Sesame', 'static/sesame.png', '{"What is Sesame Allergy?":"Sesame allergy is an immune reaction to proteins in sesame seeds.","Allergic Reactions":"Symptoms range from mild itching to life-threatening anaphylaxis."}'),
    ('Corn', 'static/corn.png', '{"What is Corn Allergy?":"Corn allergy is an adverse immune response to proteins found in corn and its derivatives.","Allergic Reactions":"Symptoms may include skin irritation, respiratory issues, and anaphylaxis."}'),
    ('Meat', 'static/meat.png', '{"What is Meat Allergy?":"Meat allergy occurs when the immune system reacts to proteins in beef, pork, lamb, or poultry.","Allergic Reactions":"Symptoms include stomach pain, hives, and in severe cases, anaphylaxis."}'),
    ('Gelatin', 'static/gelatin.png', '{"What is Gelatin Allergy?":"Gelatin allergy is a reaction to proteins in animal-derived gelatin.","Allergic Reactions":"Reactions range from mild hives to anaphylaxis."}'),
    ('Seeds', 'static/seeds.png', '{"What is Seed Allergy?":"Seed allergies include reactions to seeds like sunflower, flax, and mustard.","Allergic Reactions":"Symptoms vary from mild rashes to severe anaphylaxis."}'),
    ('Spices', 'static/spice.png', '{"What is Spice Allergy?":"Spice allergies involve reactions to seasonings like cinnamon, garlic, and paprika.","Allergic Reactions":"Symptoms include skin rashes, digestive upset, and respiratory issues."}'),
    ('Fruits', 'static/fruits.png','{"What is Fruit Allergy?":"Fruit allergies result from immune reactions to proteins in various fruits.","Allergic Reactions":"Symptoms range from oral allergy syndrome to severe anaphylaxis."}'),
    ('Tree Pollen', 'static/treepollen.png', '{"What is Tree Pollen Allergy?":"Tree pollen allergy is a seasonal allergic reaction to pollen from trees.","Allergic Reactions":"Symptoms include sneezing, itchy eyes, and asthma-like responses."}');
